### ISSUE TITLE
投影矩阵疑问

### ISSUE THREAD

**Issue by aiplay** [AsehesL/FogOfWar#2]
请问您的投影矩阵**internal_WorldToProjector**是如何推导出来的，希望能够具体说明下。

**Comment by AsehesL** [comment]
想象一下position是迷雾区域的中心坐标，xSize是迷雾区域的x轴宽度，zSize是z轴宽度，那么迷雾区域最左下角和最右上角的值就是posA(position.x-xSize*0.5, y, position.z-zSize*0.5)， posB(position.x+xSize*0.5, y, position.z+zSize*0.5)，internal_WorldToProjector的作用就是把这个区域范围内的世界坐标x,z坐标映射到一个(0,0)~(1,1)的范围内作为投影坐标，即posA会映射为projA(0,0,0)，posB映射为projB(1,1,0)。
具体计算就是:
projX = (worldX - position.x)/(xSize*0.5)*0.5+0.5 = worldX/xSize - position.x/xSize + 0.5
projY = (worldZ - position.z)/(zSize*0.5)*0.5+0.5 = worldZ/zSize - position.z/zSize + 0.5，

这其中还有一个操作就是我忽略了世界坐标的y轴坐标到投影空间的计算，因为迷雾投影是从上往下投影的，因此理论上不需要用到y轴，所以忽略了计算。
在矩阵中的表现就是m00,m03计算了世界空间x轴的值，m12和m13计算世界空间z轴的值并映射到投影坐标的y轴，而m20~m23全部设为0，即排除世界坐标y轴到投影空间的映射

**Comment by aiplay** [comment]
好的，多谢！

还有一个问题，请教一下：
在**FOWRenderer.cs**中，关于**camScale**的计算是
` float camScale = topLeft.magnitude * camera.farClipPlane / camera.nearClipPlane;`
根据《Unity Shader入门精要》中13.3章节的介绍，这个缩放因子好像是
`scale = TL / Near`

请问为什么这里会多乘一个**camre.farClipPlane**呢？

**Comment by AsehesL** [comment]
相似三角形：一开始计算的topLeft = (camera.transform.forward * camera.nearClipPlane - toRight + toTop)，表示的是相机中心点指向近裁面左上角的向量，假设记做"tlN"，最终要求的是相机中心点指向远裁面左上角的向量，记做“tlF”，那么tlN和近裁面构成的三角形和tlF和远裁面构成的三角形就是相似三角形，所以tlN/tlF = near/far。

**Comment by aiplay** [comment]
了解了，感谢！
